# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_circles(object):
    def setupUi(self, yellowcircles):
        yellowcircles.setObjectName("yellowcircles")
        yellowcircles.resize(500, 500)
        yellowcircles.setMinimumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setFamily("Niagara Engraved")
        font.setPointSize(36)
        yellowcircles.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=yellowcircles)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 140, 181, 181))
        self.pushButton.setObjectName("pushButton")
        yellowcircles.setCentralWidget(self.centralwidget)

        self.retranslateUi(yellowcircles)
        QtCore.QMetaObject.connectSlotsByName(yellowcircles)

    def retranslateUi(self, yellowcircles):
        _translate = QtCore.QCoreApplication.translate
        yellowcircles.setWindowTitle(_translate("yellowcircles", "MainWindow"))
        self.pushButton.setText(_translate("yellowcircles", "Go, Go, Go"))
